version: '3'
services:
  app:
    build: .
    ports:
      - "8093:8092"
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: notas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: stalin
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:5.0
    ports:
      - "27018:27017"

    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: